export const PathUrls = {
  projects: {
    root: "/client",
    workspaceName: "/client/[clientCode]",
    project: "/client/[clientCode]/[projectName]",
  },
  quotation: {
    root: "/quotation",
    create: "/quotation/create",
    detail: "/quotation/detail",
  },
  lts: {
    root: "/admin/dashboard",
    // dashboard: "/admin/dashboard",
    accounts: "/admin/accounts",
    subjects: "/admin/subjects",
    teaching: "/admin/teaching",
    curriculum: "/admin/curriculum",
    plos: "/admin/plos",
    clos: "/admin/clos",
    evaluation: "/admin/teaching/evaluation",
    createSubjects: "/admin/subjects/createSubject",
    createCurriculum: "/admin/curriculum/createCurriculum",
    createPlo: "/admin/plos/createPlo",
    createClo: "/admin/clos/createClo",
    createTeaching: "/admin/teaching/createTeaching",
    editSubjects: "/admin/subjects/[subNameEn]",
    editAccount: "admin/accounts/[name]",
    editTeaching: "/admin/teaching/editTeaching",
    editCurriculum: "admin/curriculum/[degreeFullEn]",
    editPlo: "admin/plos/[ploName]",
    editClo: "admin/clos/[cloName]",

    coorTeaching: "/coordinator/teaching",
    coorCreateTeaching: "/coordinator/teaching/createTeaching",
    coorEditTeaching: "/coordinator/teaching/editTeaching",
    
    instructorTeaching: "/instructor/teaching",
    instructorCreateTeaching: "/instructor/teaching/createTeaching",
    instructorEditTeaching: "/instructor/teaching/editTeaching",
  },
};
